workbench_access.settings:
  type: config_object
  label: 'Workbench Access settings'
  mapping:
    label:
      type: text
      label: 'Label shown to define a Workbench Access control group.'
    plural_label:
      type: text
      label: 'Label shown to define a set of Workbench Access control groups.'

node.type.*.third_party.workbench_access:
  type: mapping
  label: 'Per-content type access control settings'
  mapping:
    workbench_access_status:
      type: boolean
      label: 'Workbench Access status'
